### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by fredZen** [degree9/boot-npm#21]
Hi

currently, boot-npm doesn’t work on windows. That because the executable for npm is actually a wrapper called `npm.cmd`, and neither windows nor commons-exec is smart enough to slap on the `.cmd` extension when asked to execute `npm`.

I have two fixes for the problem:

- [this fix](https://github.com/fredZen/boot-npm/commit/e3694e2aedd7a9638066aae9008eae00f077f851) runs `npm` through the windows interpreter `cmd.exe`. `cmd.exe` figures out the missing extension. What I like about this solution is that it’s fairly generic. It could be pushed down at least to boot-exec, and plausibly to clj-commons-exec or even apache commons-exec
- [this other fix](https://github.com/fredZen/boot-npm/commit/d8a780fb8e557c0a14ae5d0ffe8292539bf4fd4a) just slaps on the `.cmd` extension, making it simpler than the fix above

obviously, both fixes leave the everything as usual on non-windows platforms.

Would you be interested in a pull request for one fix or the other?

**Comment by burn2delete** [comment]
Hi! I like the first fix you posted, I wonder if we could generalize that within boot-exec to allow an alternate executable when on Windows?

**Comment by fredZen** [comment]
Makes sense. I will submit a pull-request in the spirit of the first fix, but to boot-exec.
