### ISSUE TITLE
Npm warnings

### ISSUE THREAD

**Issue by arichiardi** [degree9/boot-npm#29]
Hi and thanks as usual for your good work on these libs!

With the latest `boot-css` (which contains `boot-npm` `1.10.0-SNAPSHOT`), I get the following warnings from `npm`:

```shell
Adding file to fileset... 
• ./package.json -> ./package.json 
Executing Process: npm
npm WARN saveError ENOENT: no such file or directory, open '/home/arichiardi/.boot/cache/cache/project/home/arichiardi/git/ar-website/degree9.boot-npm/cache/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/arichiardi/.boot/cache/cache/project/home/arichiardi/git/ar-website/degree9.boot-npm/cache/package.json'
npm WARN cache No description
npm WARN cache No repository field.
npm WARN cache No README data
npm WARN cache No license field.
```

Minor, maybe the task can take the info from boot or use some temporary data for `package.json`?

**Comment by burn2delete** [comment]
The task used to provide temporary data, however that changed the behavior compared to using a projects package.json, and was unreliable. It will only create the package.json once as the task caches the npm dependencies. We do need to figure out how to suppress package.lock warning.

**Comment by burn2delete** [comment]
This should be resolved now, please reopen if you still have problems.
