### ISSUE TITLE
Needs better tutorial / quick-start

### ISSUE THREAD

**Issue by YurySolovyov** [degree9/boot-npm#4]
At the moment it is not clear how to make npm module available in your application.
Say, I want to use [pluralise](https://github.com/chilts/pluralise) module, what are steps to make it available in the application?

I'd be happy to submit a PR with updated docs, but I need to figure this out for myself first.

**Comment by burn2delete** [comment]
The main goal of this boot task is to enable things like bower, grunt and other node applications from your boot build. It is capable of installing npm modules to the fileset however does not help with using them within a project, that will come later.

**Comment by burn2delete** [comment]
What kind of project are you looking to build with node modules?

**Comment by YurySolovyov** [comment]
I'm working on [eion](https://github.com/YurySolovyov/eion), it is electron project and I hoped to use npm modules to make some stuff easier.

For the moment, I "solved" the issue this way:

``` clojure
(deftask npm-install []
  (copy-resource "package.json" "target/package.json")
  (dosh "npm" "install" "target/" "--prefix" "target/"))
```

This allows me to access npm modules like:

``` clojure
(def execa (js/require "execa"))
```

But I'd be glad to find a better solution.

**Comment by burn2delete** [comment]
Awesome, I am working on a solution for just that! I would be glad to accept PRs if you have ideas, checkout #degree9/boot-electron (needs to be updated with my dev copy)

**Comment by YurySolovyov** [comment]
I used [electron-and-clojurescript](https://github.com/martinklepsch/electron-and-clojurescript), so it is kind of solved already, at least for me. 
What I really want is the ability to specify npm deps and be able to point where to install them.
Something like:

``` clojure
:npm {
  :execa "^0.5.0"
  :output-dir "target/"
}
```

**Comment by burn2delete** [comment]
Right, you are looking for

``` clj
(npm :install {:execa "^0.5.0"})
```

**Comment by burn2delete** [comment]
@YurySolovyov did that work for you?

**Comment by YurySolovyov** [comment]
Didn't had a chance to test it yet, will try today. Are you on clojurians channel in slack?

**Comment by burn2delete** [comment]
I am, feel free to find me in the boot channel.

**Comment by YurySolovyov** [comment]
My app expects that there would be `node_modules/` dir in `target/`, what should I do to make it happen?

**Comment by burn2delete** [comment]
@YurySolovyov the snippet above should work for you.

``` clojure
(npm :install {:execa "^0.5.0"})
```
