### ISSUE TITLE
Need a way to control contents of generated package.json or a way to disable it.

### ISSUE THREAD

**Issue by YurySolovyov** [degree9/boot-npm#5]
I tried this again and now it seems to work.

But next thing I that got me stuck is that you generate some custom package.json file,
contents of which I can't control.

I'd be fine it you can take entire package.json in a form of Clojure map or have a way to disable creation or copying of this file.

**Comment by burn2delete** [comment]
@YurySolovyov Can you give version `0.3.0` a try, it allows you to provide a package.edn or other file as the argument `--package` or `-p` which will be deep-merged with the map generated.

Perhaps we need an `include` option to specifically include the package.json in the output?

**Comment by burn2delete** [comment]
solved past `0.8.0`
